# 设置实际的默认编译输出目录
set(EXECUTABLE_OUTPUT_PATH "${PROJECT_BINARY_DIR}/bin")
set(ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/lib")

set(PROJECT_TARGET_INSTALL_EXECUTABLE_DIR "bin")
set(PROJECT_TARGET_INSTALL_ARCHIVE_DIR "lib")

if (WIN32)
    set(LIBRARY_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/bin")
    set(PROJECT_TARGET_INSTALL_LIBRARY_DIR "bin")
    link_directories (${LIBRARY_OUTPUT_DIRECTORY})
else ()
    set(LIBRARY_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/lib")
    set(PROJECT_TARGET_INSTALL_LIBRARY_DIR "lib")
endif ()

link_directories (${ARCHIVE_OUTPUT_DIRECTORY})